"""Provisions deleted by an amending act — the superseded-citation record.

GENERATED by ``scripts/build_superseded_index.py`` from the consolidation plan;
do not edit by hand. Each entry records a provision an amending act DELETED (so it
is absent from current consolidated law), the amendment-list point that deleted
it, and — when confidently derivable — where its substance was relocated. The
runtime guard ``application/_superseded`` reads this to catch an answer that cites
a deleted provision as if still in force (e.g. AI Act "Article 10(5)", deleted by
the Digital Omnibus and relocated to Article 4a(1)).
"""

SUPERSEDED = [
    {
        'celex': '32024R1689',
        'deleted_ref': 'Article 10(5)',
        'deleted_id': '32024R1689_010.005',
        'amender_celex': '32026R1744',
        'amender_name': 'Digital Omnibus on AI',
        'point_num': '9',
        'see_ref': 'Article 4a(1)',
        'see_id': '32024R1689_004a.001',
    },
    {
        'celex': '32024R1689',
        'deleted_ref': 'Annex I, Section A, point 1',
        'deleted_id': '32024R1689_anx_I_sec_A_1',
        'amender_celex': '32026R1744',
        'amender_name': 'Digital Omnibus on AI',
        'point_num': '41',
        'see_ref': None,
        'see_id': None,
    },
    {
        'celex': '32024R1689',
        'deleted_ref': 'Annex VIII, Section B, point 7',
        'deleted_id': '32024R1689_anx_VIII_sec_B_7',
        'amender_celex': '32026R1744',
        'amender_name': 'Digital Omnibus on AI',
        'point_num': '42',
        'see_ref': None,
        'see_id': None,
    },
    {
        'celex': '32024R1689',
        'deleted_ref': 'Annex VIII, Section B, point 9',
        'deleted_id': '32024R1689_anx_VIII_sec_B_9',
        'amender_celex': '32026R1744',
        'amender_name': 'Digital Omnibus on AI',
        'point_num': '42',
        'see_ref': None,
        'see_id': None,
    },
]
