#!/usr/bin/env python
"""Regenerate ``domain/ontology/superseded_provisions.py`` from the consolidation.

For every ``base ← amender`` pair in ``consolidation_plan()``, run the
consolidation report-only and capture the provisions it DELETED, with the
amendment-list point and the derived relocation home (see ``consolidation.superseded``).
The result is the single source of truth the runtime superseded-citation guard
(``application/_superseded``) reads — the receipt the applier otherwise discards.

Report-only: writes nothing to the graph and needs no rebuild.

    python scripts/build_superseded_index.py          # regenerate the module
    python scripts/build_superseded_index.py --check   # fail if it would change
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from consolidation.superseded import compute_superseded, record_dicts
from domain.legislation_catalog import consolidation_plan

_OUT = Path(__file__).resolve().parent.parent / "domain" / "ontology" / "superseded_provisions.py"

_HEADER = '''"""Provisions deleted by an amending act — the superseded-citation record.

GENERATED by ``scripts/build_superseded_index.py`` from the consolidation plan;
do not edit by hand. Each entry records a provision an amending act DELETED (so it
is absent from current consolidated law), the amendment-list point that deleted
it, and — when confidently derivable — where its substance was relocated. The
runtime guard ``application/_superseded`` reads this to catch an answer that cites
a deleted provision as if still in force (e.g. AI Act "Article 10(5)", deleted by
the Digital Omnibus and relocated to Article 4a(1)).
"""
'''


def _build() -> str:
    records: list[dict] = []
    for base, amender in consolidation_plan():
        records.extend(record_dicts(compute_superseded(base, amender)))
    lines = [_HEADER, "SUPERSEDED = ["]
    for r in records:
        lines.append("    {")
        for k in ("celex", "deleted_ref", "deleted_id", "amender_celex",
                  "amender_name", "point_num", "see_ref", "see_id"):
            lines.append(f"        {k!r}: {r[k]!r},")
        lines.append("    },")
    lines.append("]")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated module is stale")
    args = ap.parse_args()
    new = _build()
    if args.check:
        old = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if old != new:
            print("superseded_provisions.py is STALE — run build_superseded_index.py",
                  file=sys.stderr)
            return 1
        print("superseded_provisions.py is up to date.")
        return 0
    _OUT.write_text(new, encoding="utf-8")
    n = new.count("'deleted_ref'")
    print(f"[superseded] wrote {_OUT.relative_to(Path.cwd())} — {n} record(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
