"""Export conversation history as Markdown."""
from __future__ import annotations

from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Shared content
# ---------------------------------------------------------------------------

_FRIENDLY_INTRO = (
    "This document was generated by CRSS (Compliance Readiness Support System), "
    "a technology demonstration of AI-assisted regulatory analysis for EU medical "
    "device and AI regulations."
)

_FORMAL_DISCLAIMER = (
    "DISCLAIMER \u2014 This output is produced by a prototype system under active "
    "development. It does not constitute legal advice, regulatory guidance, or an "
    "official interpretation of any EU regulation. The content has not been reviewed "
    "or endorsed by any notified body, competent authority, or regulatory agency. "
    "Users must independently verify all regulatory conclusions with qualified legal "
    "and regulatory professionals before relying on them for compliance decisions. "
    "The developers of CRSS accept no liability for decisions made based on this output."
)

_FOOTER_LINE = "CRSS Demo \u2014 Not for regulatory use"

# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------


def generate_markdown(conversation: list[dict[str, str]]) -> str:
    """Return a well-structured Markdown document from a conversation.

    Each item in *conversation* should be ``{"role": "user"|"agent", "content": "..."}``.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# CRSS \u2014 Compliance Readiness Support System")
    lines.append("")
    lines.append("**Demo Report**")
    lines.append("")
    lines.append(f"Generated: {now}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"> {_FRIENDLY_INTRO}")
    lines.append(">")
    lines.append(f"> {_FORMAL_DISCLAIMER}")
    lines.append("")
    lines.append("---")
    lines.append("")

    q_num = 0
    for msg in conversation:
        role = msg.get("role", "")
        content = (msg.get("content") or "").strip()
        if not content:
            continue
        if role == "user":
            q_num += 1
            lines.append(f"## Question {q_num}")
            lines.append("")
            lines.append(content)
            lines.append("")
        elif role == "agent":
            lines.append(f"### Answer")
            lines.append("")
            lines.append(content)
            lines.append("")
            lines.append("---")
            lines.append("")

    # Footer disclaimer
    lines.append("")
    lines.append(f"*{_FOOTER_LINE}*")
    lines.append("")

    return "\n".join(lines)
